from enum import StrEnum


class FinalVerdict(StrEnum):
    VERIFIED_PASS = "VERIFIED_PASS"  # nosec B105
    VERIFIED_FAIL = "VERIFIED_FAIL"
    BLOCKED = "BLOCKED"
    INCOMPLETE = "INCOMPLETE"
    UNKNOWN = "UNKNOWN"


class Classification(StrEnum):
    COMMAND_RESULT = "COMMAND_RESULT"
    POLICY_DECISION = "POLICY_DECISION"
    PROVIDER_RESPONSE = "PROVIDER_RESPONSE"
    DELIVERY_VERDICT = "DELIVERY_VERDICT"


class FailureClassification(StrEnum):
    PLANNING_ERROR = "PLANNING_ERROR"
    CONTEXT_MISSING = "CONTEXT_MISSING"
    POLICY_DENIAL = "POLICY_DENIAL"
    TOOL_SCHEMA_ERROR = "TOOL_SCHEMA_ERROR"
    TOOL_RUNTIME_ERROR = "TOOL_RUNTIME_ERROR"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    TEST_FAILURE = "TEST_FAILURE"
    SCOPE_VIOLATION = "SCOPE_VIOLATION"
    CONTRACT_TAMPERING = "CONTRACT_TAMPERING"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    UNVERIFIABLE_CLAIM = "UNVERIFIABLE_CLAIM"
    MODEL_LOOP = "MODEL_LOOP"


class PushClassification(StrEnum):
    FRESH_VERIFIED_PUSH = "FRESH VERIFIED PUSH"
    VERIFIED_NO_OP = "VERIFIED NO-OP / ALREADY UP TO DATE"
    PUSH_FAILED = "PUSH FAILED"
    PUSH_NOT_ATTEMPTED = "PUSH NOT ATTEMPTED"
